/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filtering;

import DB_MYSQL.CRUD;
import StringManipulation.FilterHTML;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;

/**
 *
 * @author iranjo_sd2082
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeHTML = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOrig = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFiltered = new javax.swing.JTextArea();
        countWords = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        countedwords = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        removeHTML.setText("removeHTML");
        removeHTML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeHTMLMouseClicked(evt);
            }
        });
        removeHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeHTMLActionPerformed(evt);
            }
        });

        jTextAreaOrig.setColumns(20);
        jTextAreaOrig.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOrig);

        jTextAreaFiltered.setColumns(20);
        jTextAreaFiltered.setRows(5);
        jScrollPane2.setViewportView(jTextAreaFiltered);

        countWords.setText("countWords");
        countWords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countWordsMouseClicked(evt);
            }
        });
        countWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countWordsActionPerformed(evt);
            }
        });

        countedwords.setColumns(20);
        countedwords.setRows(5);
        jScrollPane3.setViewportView(countedwords);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(removeHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(countWords, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countWords, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeHTML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeHTMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeHTMLMouseClicked
        // TODO add your handling code here:
        String str = jTextAreaOrig.getText();
        FilterHTML f = new FilterHTML();
        str = f.removeHTML(str);
        jTextAreaFiltered.setText(str);
    }//GEN-LAST:event_removeHTMLMouseClicked

    private void removeHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeHTMLActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_removeHTMLActionPerformed

    private void countWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countWordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countWordsActionPerformed

    private void countWordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countWordsMouseClicked

        CRUD c = new CRUD();

        String sentence = jTextAreaFiltered.getText();
        String[] words = sentence.split("\\W");
//        CONTAINER OF EVERY WORDS no repeat
        ArrayList<String> uniqueWords = new ArrayList();
        ArrayList<String> finalOutput = new ArrayList();
        String output = "";
        for (String word : words) {
            if (!uniqueWords.contains(word) && !word.isEmpty()) {
                uniqueWords.add(word);
            }
        }
        for (String text : uniqueWords) {
            int counter = 0;
            for (String original : words) {
                if (original.equals(text)) {
                    counter++;
                }
            }
            finalOutput.add(text + " = " + counter);
            try {
                // create a mysql database connection
                String myDriver = "com.mysql.jdbc.Driver";
                String myUrl = "jdbc:mysql://localhost/bigdata";
                Class.forName(myDriver);
                Connection conn = DriverManager.getConnection(myUrl, "root", "");

//                // create a sql date object so we can use it in our INSERT statement
//                Calendar calendar = Calendar.getInstance();
//                java.sql.Date startDate = new java.sql.Date(calendar.getTime().getTime());

                // the mysql insert statement
                String query = " insert into bigdata(words,count,school)"
                        + " values (?,?,?)";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = (PreparedStatement) conn.prepareStatement(query);
                preparedStmt.setString(1, text);
                preparedStmt.setInt(2, counter);
              preparedStmt.setString (3,"USC");

                // execute the preparedstatement
                preparedStmt.execute();

                conn.close();
            } catch (Exception e) {
                System.err.println(e);

            }
        }
        for (String res : finalOutput) {
            output += res + "\n";
        }
        countedwords.setText(output);


    }//GEN-LAST:event_countWordsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countWords;
    private javax.swing.JTextArea countedwords;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaFiltered;
    private javax.swing.JTextArea jTextAreaOrig;
    private javax.swing.JButton removeHTML;
    // End of variables declaration//GEN-END:variables
}
